Feature/ob 7
obox-dev/obox_frontend pull request #62
Opened 2023-11-09 01:04 UTC by ptrodion

2023-11-09 13:20 UTC, y-andriievskyi requested changes

2023-11-09 13:20 UTC, y-andriievskyi commented on shared/src/components/atoms/InputLabel/types.ts
>    className?: string;
do we still need props className & wrapperClassName?

2023-11-09 13:20 UTC, y-andriievskyi commented on shared/src/components/molecules/Dialog/Dialog.scss
> +  // We use "sm" for useDeleteMenu modal window
Probably you meant We use "xl"

2023-11-09 13:20 UTC, y-andriievskyi commented on package.json
> +    "husky": "^8.0.3",
Lock versions for husky and lint-staged

2023-11-09 13:20 UTC, y-andriievskyi commented on admin/src/pages/Menu/components/MenuCategories/hooks/useCreateCategory.tsx
> +        name: ' ',
Why there's a space? Should be empty string by default

2023-11-09 13:27 UTC, y-andriievskyi requested changes

2023-11-09 13:27 UTC, y-andriievskyi commented on shared/src/components/molecules/Dialog/Dialog.scss
> +  $header-marButt,
Bad naming for variables:
1) right, top, padding - right/top for what, padding of what? The structure of mixin is not that simple and It should be obvious for other team members what is expected to be passed as parameters.
2) header-marButt - try to avoid shortcuts like mar, bot etc.

2023-11-09 17:36 UTC, anastasia1383 requested changes

2023-11-09 17:36 UTC, anastasia1383 commented on shared/src/components/molecules/Dialog/Dialog.scss
> +      .input-label {
input styles should be placed inside input component styles to apply them for all inputs in the system

2023-11-09 17:36 UTC, anastasia1383 commented on shared/src/components/molecules/Dialog/Dialog.scss
> +      .btn {
also check buttons and other general components for common general styles

2023-11-09 23:31 UTC, ptrodion commented on admin/src/pages/Menu/components/MenuCategories/hooks/useCreateCategory.tsx
> +        name: ' ',
Corrected, I think it had something to do with the initial confusion with the EsLint

2023-11-09 23:35 UTC, ptrodion commented on package.json
> +    "husky": "^8.0.3",
Can you just not accept this file?

2023-11-09 23:40 UTC, ptrodion commented on shared/src/components/atoms/InputLabel/types.ts
>    className?: string;
I think we need it for now, until we create the function we discussed (class name helper), If we remove it now, the first character in the class name will be a space.

2023-11-09 23:42 UTC, ptrodion commented on shared/src/components/molecules/Dialog/Dialog.scss
> +      .input-label {
Ok, then I'll remove it and we'll need to discuss the task of adding these styles.

2023-11-12 16:25 UTC, ptrodion commented on shared/src/components/atoms/InputLabel/types.ts
>    className?: string;
Worked it out with you, cleaned it up.

2023-11-12 16:26 UTC, ptrodion commented on shared/src/components/molecules/Dialog/Dialog.scss
> +  // We use "sm" for useDeleteMenu modal window
Corrected.

2023-11-12 16:26 UTC, ptrodion commented on package.json
> +    "husky": "^8.0.3",
Worked it out with you, cleaned it up.

2023-11-12 16:26 UTC, ptrodion commented on admin/src/pages/Menu/components/MenuCategories/hooks/useCreateCategory.tsx
> +        name: ' ',
Worked it out with you, cleaned it up.

2023-11-12 16:27 UTC, ptrodion commented on shared/src/components/molecules/Dialog/Dialog.scss
> +  $header-marButt,
Changed the structure, simplified, changed names

2023-11-12 16:28 UTC, ptrodion commented on shared/src/components/molecules/Dialog/Dialog.scss
> +      .input-label {
Made generic styles for: Input - Label - Button -TextArea

2023-11-12 16:29 UTC, ptrodion commented on shared/src/components/molecules/Dialog/Dialog.scss
> +      .btn {
Added all text and backgrounds for buttons to variables, actively used in the Button component

2023-11-12 17:00 UTC, y-andriievskyi requested changes

2023-11-12 17:00 UTC, y-andriievskyi commented on shared/src/components/molecules/Dialog/Dialog.scss
> +  $isButton-delte
bad spelling
install SpellChecker plugin for VScode it will help with such issues

2023-11-12 17:00 UTC, y-andriievskyi commented on shared/src/components/atoms/Textarea/Textarea.tsx
> +      <p className="textarea-count">
I'd make this a conditional part of a template.
We might have a textareas without counter.
Probably the best solution would also be to move it to a separate component.

2023-11-12 17:20 UTC, ptrodion commented on shared/src/components/molecules/Dialog/Dialog.scss
> +  $isButton-delte
Changed. Made commit.

2023-11-15 22:11 UTC, ptrodion commented on shared/src/components/atoms/Textarea/Textarea.tsx
> +      <p className="textarea-count">
Now I left it as it is, but in case we will make a function by class names we can apply here as well

2023-11-16 00:59 UTC, y-andriievskyi approved these changes

2023-11-16 00:59 UTC, merged